name: Build Android APK

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build release APK
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          bash tool/build_android_release.sh

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: matjar-aljanoub-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
